start_flask:
  default:
    languages:
      - python3.10
    steps:
      - run: mkdir -p python
        path: ./code
      - run: pip install -r requirements.txt -t ./python
        path: ./code
  defaultBuilder:
    languages:
      - python3.10
    steps:
      - run: mkdir -p python
        path: ./code
      - run: pip install -r requirements.txt -t ./python
        path: ./code