#!/bin/sh

MATCH="^[[:space:]]*($|;)"

echo "==== Additional PHP 7.2 information ====" >&3
echo "" >&3
echo "++++ PHP @PHP_VERSION SAPI (php7.2query -S): ++++" >&3
/usr/sbin/php7.2query -S >&3
echo "" >&3
echo "++++ PHP 7.2 Extensions (php7.2query -M -v): ++++" >&3
/usr/sbin/php7.2query -M -v >&3
echo "" >&3

echo "++++ Configuration files: ++++" >&3
for dsoname in readline; do
    inifile=${dsoname}.ini
    echo "**** /etc/php/7.2/mods-available/$dsoname.ini ****" >&3
    grep -Ev "$MATCH" "/etc/php/7.2/mods-available/$dsoname.ini" >&3
    echo "" >&3
done
