start_gin:
  default:
    languages:
      - go1.18
    cache:
      paths:
        - "$GOPATH/pkg/mod"
    steps:
      - run: go mod tidy
        path: ./myapp
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main
        path: ./myapp