INSERT INTO met_language VALUES (null, 'system', '系统参数', 0, 1, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'search', '搜索', 0, 16, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'home', '网站首页', 0, 17, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'success', '操作成功!', 0, 19, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Title', '标题', 0, 24, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Content', '内容', 0, 25, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Online', '在线交流', 0, 30, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Noinfo', '没有了', 0, 32, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'displayimg', '展示图片', 0, 40, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'default', '默认', 0, 41, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membercode', '验证码错误！', 0, 1, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberpassno', '密码错误！', 0, 3, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'access', '您没有阅读该信息的权限！', 0, 4, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'login', '登录', 0, 5, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'register', '注册', 0, 6, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Page', '页', 0, 2, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PagePre', '上一页', 0, 6, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageNext', '下一页', 0, 7, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PageGo', '转至第', 0, 8, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberLogin', '会员登录', 0, 2, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberPassword', '请输入密码', 0, 4, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberName', '会员名', 0, 6, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberImgCode', '验证码', 0, 8, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberTip1', '看不清？点击更换验证码', 0, 9, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberGo', '登录', 0, 11, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberRegister', '立即注册', 0, 12, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberForget', '忘记密码？', 0, 14, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex3', '会员中心', 0, 17, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex9', '个人信息', 0, 23, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberIndex10', '退出登录', 0, 24, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicUserName', '用户名', 0, 32, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicCell', '手机', 0, 38, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicLoginNum', '登录次数', 0, 40, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicLastIP', '最后登录IP', 0, 42, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbasicType', '会员类型', 0, 50, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberReg', '会员注册', 0, 58, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberDetail', '查看', 0, 60, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messageeditorReply', '管理员回复留言', 0, 74, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getNotice', '会员找回密码', 0, 83, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'NoidJS', '没有此用户', 0, 87, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip1', '您的密码重置请求已经得到验证。请点击以下链接输入您的新密码：', 0, 89, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip2', '取回密码的方法已经通过 Email 发送到您的信箱中。请在 3 天之内到网站修改您的密码。', 0, 90, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip3', '您提交的找回密码邮件发送失败！请联系网站管理员！。', 0, 91, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getTip5', '密码找回', 0, 93, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getOK', '发送成功', 0, 97, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getFail', '发送失败', 0, 98, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membernodo', '该用户尚未激活，请即时与管理员联系!', 0, 99, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'hello', '您好！', 0, 100, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fileOK', '文件上传成功', 0, 1, 5, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js1', '操作失败！', 0, 1, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js2', '管理员身份登录！', 0, 2, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js4', '无法激活此用户,请与管理员联系！', 0, 4, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js5', '已成功激活,请登录！', 0, 5, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js6', '用户名输入有误!', 0, 6, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js7', '用户名不能小于3位', 0, 7, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js10', '两次密码输入不一致', 0, 10, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js14', '请输入验证码！', 0, 14, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js15', '此用户名已经被使用', 0, 15, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js16', '会员激活', 0, 16, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js18', '请您点击', 0, 18, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js23', '文件格式不允许上传。', 0, 23, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js25', '注册成功！', 0, 25, 6, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Download', '点击下载', 0, 8, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Submit', '提交信息', 0, 16, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'TextLink', '文字链接', 0, 34, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'PictureLink', '图片链接', 0, 35, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Contact', '联系方式', 0, 36, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'ApplyLink', '申请友情链接', 0, 37, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SubmitInfo', '提交留言', 0, 39, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Reply', '管理员回复', 0, 42, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback1', '请不要在', 0, 49, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback2', '秒内重复提交信息，谢谢合作！', 0, 50, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback3', '反馈信息中不能包含', 0, 51, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback5', '反馈已经被关闭', 0, 52, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AddTime', '提交时间', 0, 55, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SourcePage', '来源页面', 0, 56, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Feedback4', '反馈信息已成功提交，谢谢！', 0, 57, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Choice', '请选择', 0, 58, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Empty', '不能为空', 0, 59, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo1', '在线留言', 0, 63, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo2', '您的留言已成功提交，谢谢！', 0, 64, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'MessageInfo5', '该留言功能已经被关闭', 0, 67, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo1', '请输入搜索关键词！', 0, 71, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo2', '全站搜索', 0, 72, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo3', '没有含有', 0, 73, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'SearchInfo4', '的信息内容', 0, 74, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Job1', '不限', 0, 75, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cvtitle', '在线应聘', 0, 78, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'cv', '查看简历', 0, 79, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'wap', '手机版', 0, 87, 7, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fliptext1', '查看更多', 0, 48, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'fliptext2', '加载中...', 0, 49, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'downloadtext1', '下载', 0, 50, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'tagweb', '标签', 0, 66, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror1', '请填写此字段。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror2', '请从这些选项中选择一个。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror3', '请输入正确的手机号码。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror4', '请输入正确的Email地址。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror5', '两次输入的密码不一致，请重新输入。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror6', '请输入至少&metinfo&个字符。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror7', '输入不能超过&metinfo&个字符。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formerror8', '输入的字符数必须在&metinfo&之间。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'read', '阅读', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js46', '不能重复', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips1', '感谢您的注册！激活链接已经发送到您的邮箱', 0, 103, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips2', '点击邮件里的链接即可激活账户', 0, 104, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips3', '还没收到确认邮件？', 0, 105, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips4', '尝试到广告邮件、垃圾邮件目录里找找看', 0, 106, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailchecktips5', '再次发送确认邮件', 0, 107, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsafe', '账号安全', 0, 108, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'resend', '重发', 0, 109, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getmemberImgCode', '获取验证码', 0, 110, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'password', '密码', 0, 113, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userhave', '用户名已存在', 0, 114, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailhave', '邮箱已被注册', 0, 115, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberemail', '邮箱', 0, 116, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberMoreInfo', '更多资料', 0, 117, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'select', '选择', 0, 118, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'acchave', '已有账号？', 0, 119, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accpassword', '帐号密码', 0, 120, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips1', '用于保护帐号信息和登录安全', 0, 121, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modify', '修改', 0, 122, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accemail', '邮箱绑定', 0, 123, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips2', '邮箱绑定可以用于登录帐号，重置密码或其他安全验证', 0, 124, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'acctel', '手机绑定', 0, 125, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips3', '手机绑定可以用于登录帐号，重置密码或其他安全验证', 0, 126, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifypassword', '密码修改', 0, 127, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'oldpassword', '原密码', 0, 128, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newpassword', '新密码', 0, 129, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'confirm', '确定', 0, 130, 1, 1, 'cn');
INSERT INTO met_language VALUES (null, 'cancel', '取消', 0, 131, 1, 1, 'cn');
INSERT INTO met_language VALUES (null, 'emailaddress', '邮箱地址', 0, 132, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telnum', '手机号码', 0, 134, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'teluse', '手机号码已被绑定', 0, 135, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telok', '请输入正确的手机号码', 0, 136, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyacctel', '修改手机绑定', 0, 137, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyinfo', '保存资料', 0, 138, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailnow', '当前邮箱：', 0, 139, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newemail', '新邮箱', 0, 140, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifyaccemail', '修改绑定邮箱', 0, 142, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'renewpassword', '重复密码', 0, 144, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'inputcode', '请输入验证码', 0, 145, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'next', '下一步', 0, 146, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'logintips', '用户名/邮箱/手机', 0, 147, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'otherlogin', '其它方式登录', 0, 148, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'logintips1', '没有账号？现在去注册', 0, 149, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'rememberImgCode', '重发验证码', 0, 150, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'relogin', '返回登录', 0, 151, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'getpasswordtips', '邮箱/手机', 0, 152, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regclose', '注册功能已关闭', 0, 153, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regfail', '注册失败', 0, 154, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'codetimeout', '验证码已超时', 0, 155, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telcheckfail', '手机号码与短信验证号码不一致', 0, 156, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'regsuc', '注册成功！', 0, 157, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'activesuc', '激活成功，请登录！', 0, 158, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips1', '验证信息错误', 0, 159, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips2', '验证信息错误或已超时', 0, 160, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'telreg', '手机号已被注册', 0, 161, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Sendfrequent', '发送过于频繁，请稍后再试', 0, 162, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsuc', '邮件发送成功！', 0, 163, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailfail', '邮件发送失败，请确认邮箱是否正确或联系网站管理人员解决。', 0, 164, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifysuc', '修改成功', 0, 165, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'binding', '绑定', 0, 166, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'notbound', '未绑定', 0, 167, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accnotmodify', '帐号无法修改', 0, 168, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsuclink', '邮件发送成功！请点击邮件里的验证链接完成操作！', 0, 169, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'bindingok', '绑定成功', 0, 170, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'opfail', '操作失败', 0, 171, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'modifypasswordsuc', '密码修改成功！', 0, 172, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'lodpasswordfail', '原密码错误', 0, 173, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror1', '用户名或密码错误', 0, 174, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror2', '请开启session！', 0, 175, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror3', '授权失败', 0, 176, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror4', '未知错误', 0, 177, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror6', '账号未激活，请联系管理员', 0, 174, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailsucpass', '密码找回邮件已经发送至您的邮箱，点击邮件里的链接即可重设密码。', 0, 178, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailvildtips3', '请输入正确的邮箱或手机号码', 0, 179, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'membererror5', '发送失败！错误码：', 0, 180, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'noempty', '此项不能为空', 0, 181, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usernamecheck', '用户名必须在2-30个字符之间', 0, 182, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'passwordcheck', '密码必须在6-30个字符之间', 0, 183, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'passwordsame', '两次密码输入不一致', 0, 184, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'emailcheck', '请输入正确的Email地址', 0, 184, 4, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Previous_news', '上一篇', 0, 9, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'Next_news', '下一篇', 0, 10, 3, 0, 'cn');
INSERT INTO met_language VALUES (null, 'close', '关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'browserupdatetips', '你正在使用一个过时的浏览器。请升级你的浏览器，以提高您的体验。', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'newFeedback', '收到了新的反馈', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'opfailed', '操作失败', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'jobPrompt', '收到了新的简历', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'reMessage1', '您的网站', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'reMessage2', '，请尽快登录网站后台查看', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'messagePrompt', '收到了新的留言', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'formaterror', '格式错误', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listcom', '推荐', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listnew', '最新', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listhot', '热门', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'weball', '全部', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'columnall', '全部栏目', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips4', '绑定用户证实身份信息', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'rnvalidate', '实名认证', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'notauthen', '未认证', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'authen', '已认证', 0, 9, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'realname', '真实姓名', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idcode', '身份证号码', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idvalidok', '实名认证成功', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'idvalidfailed', '实名认证失败', 0, 9, 2, 0, 'cn');
INSERT INTO met_language VALUES (null, 'systips1', '您没有权限访问这个内容！请登录后访问！', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'systips2', '您所在用户组没有权限访问这个内容！', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usercheckok', '验证成功！', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usereadinfo', '阅读权限值必需大于0', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userselectname', '选项卡', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userwenxinclose', '微信登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userwenboclose', '微博登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userqqclose', 'QQ登录功能已关闭', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userbuy', '购买', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'userbuylist', '订单', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usesendcode', '验证码为', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'usesendcodeinfo', '请及时输入验证', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'feedbackinquiry', '在线询价', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'templatesusererror', '当前语言模板未配置或模板文件不存在', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'phonecode', '获取手机验证码', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'phonecodeerror', '手机验证码错误', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'memberbuytitle', '付费升级会员组', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'img_px_tips', '图片尺寸超出系统限制(图片宽高不超过2600px)', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'member_cv', '简历', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'please_login', '请先登录！', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'user_agreement', '用户协议', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'user_agreement_tips1', '我已认真阅读', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'user_agreement_tips2', '并同意注册', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'user_agreement_tips3', '请阅读并勾选同意', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'tag', 'TAG标签', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'columnSearchInfo', '请输入你感兴趣的关键词', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'advancedSearchInfo', '请输入你感兴趣的关键词', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'notemptips', '当前语言没有设置网站模板，请到“风格-网站模板”中选择1套模板', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'AddDate', '发布时间', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'listsales', '销量', 0, 0, 0, 0, 'cn');

INSERT INTO met_language VALUES (null, 'jsok', '操作成功', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'jslang3', '没有选中的记录', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'delete_information', '您确定要删除该信息吗？删除之后无法再恢复。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'js49', '撤销。', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'weixinunbind', '你确定是否要解绑微信？', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'bindweixin', '微信绑定', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'accsaftips5', '微信绑定可以用于登录帐号，消息通知等功能', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'bound', '已绑定', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'unbind', '解绑', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'weixin_login_error', '当前语言不可使用微信登录', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'login_ok', '登录成功', 0, 0, 1, 0, 'cn');
INSERT INTO met_language VALUES (null, 'new_registe_email_content', '你的网站 {webname} 收到新用户：{username} 的注册请求，请登录网站后台查看。', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'new_registe_sms_content', '你的网站 {webname} 收到新用户：{username} 的注册请求，请登录网站后台查看。', 0, 0, 0, 0, 'cn');
INSERT INTO met_language VALUES (null, 'new_regist_notice', '网站新增会员通知', 0, 0, 0, 0, 'cn');


#系统配置
INSERT INTO met_config VALUES (null, 'debug','0','',0,0,'cn');
INSERT INTO met_config VALUES (null, 'metconfig_skin_user', 'metv7', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_listtime', 'Y-m-d', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_contenttime', 'Y-m-d H:i:s', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabok', '3', '', 0, 0, 'cn');
#SEO-参数设置
INSERT INTO met_config VALUES (null, 'metconfig_hometitle', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_title_type', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_alt', '图片关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_atitle', '链接关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_linkname', 'Mituo', '', 0, 0, 'cn');
#SEO-TAG标签设置
INSERT INTO met_config VALUES (null, 'tag_show_range', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'tag_show_number', '4', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'tag_search_type', 'module', '', 0, 0, 'cn');
#SEO-404页面内容
INSERT INTO met_config VALUES (null, 'metconfig_404content', '404错误，页面不见了。。。', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_data_null', '没有找到数据', '', 0, 0, 'cn');
#SEO-优化文字设置
INSERT INTO met_config VALUES (null, 'metconfig_foottext', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_seo', '<p>后台-营销-SEO-头部优化文字处修改</p>', '', 0, 0, 'cn');
#SEO-静态及伪静态配置
INSERT INTO met_config VALUES (null, 'metconfig_webhtm', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmtype', 'html', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmpagename', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_listhtmltype', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmlistname', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmway', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_htmlurl', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_pseudo', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_defult_lang', '0', '0', 0, 0, 'cn');
#SEO-siteMap
INSERT INTO met_config VALUES (null, 'metconfig_sitemap_auto', '1', '', 0, 0, 'cn');

#客服配置
INSERT INTO met_config VALUES (null, 'metconfig_online_skin', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_type', '4', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_color', '#1baadb', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_onlinetel', '<p>服务热线：<br/>000-000-0000</p>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_x', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_online_y', '300', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_onlinenameok', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_type', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_taobao_type', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_alibaba_type', '10', '', 0, 0, 'cn');

#基本设置-网站信息
INSERT INTO met_config VALUES (null, 'metconfig_webname', '网站名称', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_logo', '../upload/201801/1515549638.png', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_mobile_logo', '../upload/201807/1532137488.png', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_logo_keyword', 'Logo关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_keywords', '网站关键词', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_description', '网站描述，一般显示在搜索引擎搜索结果中的描述文字，用于介绍网站，吸引浏览者点击。', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footright', '我的网站 版权所有 2008-2021', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footaddress', '本页面内容为网站演示数据，前台页面内容都可以在后台修改。', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_foottel', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footother', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_icp_info', ' 湘ICP备8888888号', '', 0, 0, 'cn');
#基本设置-邮箱配置
INSERT INTO met_config VALUES (null, 'metconfig_fd_fromname', '米拓信息', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_smtp', '61.152.188.131', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_usename', 'test@mail.metinfo.cn', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_password', 'passwordhidden', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_port', '25', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_way', 'tls', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_fd_word', '', '', '0', '0', 'cn');
#基本设置-三方代码设置
INSERT INTO met_config VALUES (null, 'metconfig_footstat','<script>\r\nvar _hmt = _hmt || [];\r\n(function() {\r\n  var hm = document.createElement("script");\r\n  hm.src = "https://hm.baidu.com/hm.js?520556228c0113270c0c772027905838";\r\n  var s = document.getElementsByTagName("script")[0]; \r\n  s.parentNode.insertBefore(hm, s);\r\n})();\r\n</script>','',0,0,'cn');
INSERT INTO met_config VALUES (null, 'metconfig_headstat', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_headstat_mobile', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_footstat_mobile','<script>\r\nvar _hmt = _hmt || [];\r\n(function() {\r\n  var hm = document.createElement("script");\r\n  hm.src = "https://hm.baidu.com/hm.js?520556228c0113270c0c772027905838";\r\n  var s = document.getElementsByTagName("script")[0]; \r\n  s.parentNode.insertBefore(hm, s);\r\n})();\r\n</script>','',0,0,'cn');

#基本设置-水印图
INSERT INTO met_config VALUES (null, 'metconfig_big_wate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_wate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_class', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_img', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_wate_bigimg', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_wate', 'MetInfo', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_size', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_bigsize', '35', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_color', '#000000', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_text_angle', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_watermark', '0', '', 0, 0, 'cn');
#基本设置-缩略图
INSERT INTO met_config VALUES (null, 'metconfig_autothumb_ok', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_kind', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_x', '800', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_y', '500', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_x', '800', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_y', '500', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_x', '800', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_y', '500', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_x', '800', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_y', '500', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_x', '800', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_y', '500', '', 0, 0, 'cn');

#安全设置-安全与效率
INSERT INTO met_config VALUES (null, 'metconfig_img_rename', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'access_type', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (NULL, 'metconfig_logs', 0, '', '0', '0', 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_auto_play_pc', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_auto_play_mobile', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_memberlogin_code', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_login_code', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_file_maxsize', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_file_format', 'rar|zip|sql|doc|docx|pdf|jpg|xls|png|gif|mp3|mp4|jpeg|bmp|swf|flv|ico|csv', '', 0, 0, 'cn');
#用户设置-会员设置
INSERT INTO met_config VALUES (null, 'metconfig_member_use', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_register', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_vecan', '4', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgcolor', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgimage', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_agreement', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_agreement_content', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_bg_range', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_login_box_position', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_new_registe_email_notice', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_to_admin_email', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_new_registe_sms_notice', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_to_admin_sms', '', '', 0, 0, 'cn');

#用户设置-邮件内容设置
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_title', '{webname} 会员中心 注册验证', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 注册验证, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">请勿回复本邮件, 此邮箱未受监控, 您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_title', '{webname} 会员中心 密码找回', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 密码找回, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">请勿回复本邮件, 此邮箱未受监控, 您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_title', '{webname} 会员中心 修改绑定邮箱', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} 会员中心</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">您好：</p><p style=\"line-height: 23.7999992370605px;\">这是您在 {webname} 会员中心 上的重要邮件, 功能是进行&nbsp;会员中心 绑定邮箱修改, 请点击下面的连接完成验证</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">请点击链接继续：{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131,131);\">请勿回复本邮件,此邮箱未受监控,您不会得到任何回复。<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}会员中心</strong></a></p></div></div>', '', 0, 0, 'cn');
#用户设置-社会化登录
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appkey', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_qq_open', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appid', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appsecret', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_token', '', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_auto_register', '', '', 0, 0, 'cn');
#用户设置-实名
INSERT INTO met_config VALUES (null, 'metconfig_member_idvalidate', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_idvalid_key', '', '', 0, 0, 'cn');

#页面配置
INSERT INTO met_config VALUES (null, 'metconfig_pnorder', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_product_page', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_page', '0', '', 0, 0, 'cn');
#页面配置-产品选项卡
INSERT INTO met_config VALUES (null, 'metconfig_productTabname', '详细信息', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_1', '规格参数', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_2', '包装', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_3', '选项卡四', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_4', '选项卡五', '', 0, 0, 'cn');
#页面配置-分页条数
INSERT INTO met_config VALUES (null, 'metconfig_product_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_news_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_download_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_img_list', '8', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_job_list', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_message_list', '10', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'metconfig_search_list', '10', '', 0, 0, 'cn');

#页面搜索设置
INSERT INTO met_config VALUES (null, 'global_search_range', 'all', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'global_search_type', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'global_search_module', '2', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'global_search_column', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'global_search_weight', '1|2|3|4|5|6', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'column_search_range', 'parent', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'column_search_type', '0', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'advanced_search_range', 'all', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'advanced_search_type', '1', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'advanced_search_column', '3', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'advanced_search_linkage', '1', '', 0, 0, 'cn');


INSERT INTO met_lang VALUES (null,'简体中文','1','1','cn','cn','cn.gif','','0','0','html','','cn');

INSERT INTO met_admin_array VALUES(1,'普通会员','','0','','0','0','1','1','cn','');
INSERT INTO met_admin_array VALUES(2,'代理商','','0','','0','0','2','1','cn','');

INSERT INTO `met_user_group` VALUES(1, '普通会员', 1, 'cn');
INSERT INTO `met_user_group` VALUES(2, '代理商', 3, 'cn');