INSERT INTO met_language VALUES (null, 'system', 'System parameters', 0, 1, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'search', 'search for', 0, 16, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'home', 'Home page', 0, 17, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'success', 'Successful operation!', 0, 19, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'Title', 'title', 0, 24, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'Content', 'content', 0, 25, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'Online', 'online chating', 0, 30, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'Noinfo', 'No more', 0, 32, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'displayimg', 'Show pictures', 0, 40, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'default', 'default', 0, 41, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'membercode', 'Verification code error!', 0, 1, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberpassno', 'wrong password!', 0, 3, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'access', 'You do not have permission to read this information!', 0, 4, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'login', 'log in', 0, 5, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'register', 'registered', 0, 6, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'Page', 'page', 0, 2, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'PagePre', 'Previous page', 0, 6, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'PageNext', 'Next page', 0, 7, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'PageGo', 'Go to No.', 0, 8, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberLogin', 'Member Login', 0, 2, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberPassword', 'Please enter the password', 0, 4, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberName', 'Member name', 0, 6, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberImgCode', 'Verification code', 0, 8, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberTip1', 'Can not see? Click to change verification code', 0, 9, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberGo', 'log in', 0, 11, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberRegister', 'Sign up now', 0, 12, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberForget', 'forget password?', 0, 14, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberIndex3', 'Member Centre', 0, 17, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberIndex9', 'Personal information', 0, 23, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberIndex10', 'Logout', 0, 23, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbasicUserName', 'username', 0, 32, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbasicCell', 'Phone', 0, 38, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbasicLoginNum', 'Login times', 0, 40, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbasicLastIP', 'Finally login IP', 0, 42, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbasicType', 'Type of membership', 0, 50, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberReg', 'Sign Up', 0, 58, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberDetail', 'View', 0, 60, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'messageeditorReply', 'Administrator reply message', 0, 74, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getNotice', 'Member retrieve password', 0, 83, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'NoidJS', 'Without this user', 0, 87, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getTip1', 'Your password reset request has been verified. Please click the following link to enter your new password:', 0, 89, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getTip2', 'The method of retrieving the password has been sent to your mailbox by email. Please change your password to the website within 3 days.', 0, 90, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getTip3', 'Your submitted password recovery email failed to send! Please contact the webmaster! .', 0, 91, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getTip5', 'recover password', 0, 93, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getOK', 'Sent successfully', 0, 97, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getFail', 'Failed to send', 0, 98, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membernodo', 'The user has not activated yet, please contact the administrator immediately!', 0, 99, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'hello', 'Hello!', 0, 100, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'fileOK', 'File upload is successful', 0, 1, 5, 0, 'en');
INSERT INTO met_language VALUES (null, 'js1', 'operation failed!', 0, 1, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js2', 'Administrator login!', 0, 2, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js4', 'Can not activate this user, please contact the administrator!', 0, 4, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js5', 'Has been activated, please login!', 0, 5, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js6', 'user name input error!', 0, 6, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js7', 'User name can not be less than 3 digits', 0, 7, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js10', 'The password input is inconsistent twice', 0, 10, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js14', 'please enter verification code!', 0, 14, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js15', 'This username has been used', 0, 15, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js16', 'Member activation', 0, 16, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js18', 'Please click', 0, 18, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js23', 'File format does not allow uploading.', 0, 23, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'js25', 'Registration is successful, please click the verification link in the mailbox to activate the account!!', 0, 25, 6, 0, 'en');
INSERT INTO met_language VALUES (null, 'Download', 'click to download', 0, 8, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Submit', 'Submit Information', 0, 16, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'TextLink', 'Text link', 0, 34, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'PictureLink', 'image link', 0, 35, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Contact', 'Contact information', 0, 36, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'ApplyLink', 'Apply for a friendship link', 0, 37, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SubmitInfo', 'Submit Message', 0, 39, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Reply', 'Administrator reply', 0, 42, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Feedback1', 'Please do not be there', 0, 49, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Feedback2', 'Seconds to submit information, thank you for your cooperation!', 0, 50, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Feedback3', 'Feedback can not be included', 0, 51, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Feedback5', 'Feedback has been closed', 0, 52, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'AddTime', 'Submit time', 0, 55, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SourcePage', 'Source page', 0, 56, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Feedback4', 'Feedback has been submitted, thank you!', 0, 57, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Choice', 'please choose', 0, 58, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'Empty', 'Can not be empty', 0, 59, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'MessageInfo1', 'Online message', 0, 63, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'MessageInfo2', 'Your message has been successfully submitted, thank you!', 0, 64, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'MessageInfo5', 'Message has been closed', 0, 67, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SearchInfo1', 'Enter search keywords!', 0, 71, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SearchInfo2', 'Site Search', 0, 72, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SearchInfo3', 'Not included', 0, 73, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'SearchInfo4', 'Information content', 0, 74, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'Job1', 'Not limited to', 0, 75, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'cvtitle', 'apply online', 0, 78, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'cv', 'View your resume', 0, 79, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'wap', 'Mobile version', 0, 87, 7, 0, 'en');
INSERT INTO met_language VALUES (null, 'fliptext1', 'see more', 0, 48, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'fliptext2', 'Loading...', 0, 49, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'downloadtext1', 'download', 0, 50, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'tagweb', 'label', 0, 66, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror1', 'Please fill in this field.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror2', 'Please choose one of these options.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror3', 'Please enter the correct phone number.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror4', 'Please enter the correct email address.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror5', 'The password entered twice is different. Please re-enter it.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror6', 'Please enter at least & metinfo & characters.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror7', 'Input can not exceed & metinfo & characters.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'formerror8', 'The number of characters entered must be between & metinfo &.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'read', 'read', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'js46', 'Can not repeat', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailchecktips1', 'Thank you for your registration! The activation link has been sent to your email', 0, 103, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailchecktips2', 'Click the link in the email to activate the account', 0, 104, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailchecktips3', 'Have not received confirmation email?', 0, 105, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailchecktips4', 'Try to find the advertising mail, spam directory look', 0, 106, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailchecktips5', 'Send a confirmation email again', 0, 107, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsafe', 'Account safe', 0, 108, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'resend', 'Resend', 0, 109, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getmemberImgCode', 'get verification code', 0, 110, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'password', 'password', 0, 113, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'userhave', 'Username already exists', 0, 114, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailhave', 'E-mail has been registered', 0, 115, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberemail', 'mailbox', 0, 116, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberMoreInfo', 'more info', 0, 117, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'select', 'select', 0, 118, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'acchave', 'Already have an account?', 0, 119, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accpassword', 'account password', 0, 120, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsaftips1', 'Used to protect account information and login security', 0, 121, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modify', 'modify', 0, 122, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accemail', 'Mailbox binding', 0, 123, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsaftips2', 'Mailbox bindings can be used to log in to an account, reset password, or other security verification', 0, 124, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'acctel', 'Phone binding', 0, 125, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsaftips3', 'Phone bindings can be used to log in to an account, reset password, or other security verification', 0, 126, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifypassword', 'change Password', 0, 127, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'oldpassword', 'old password', 0, 128, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'newpassword', 'new password', 0, 129, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'confirm', 'determine', 0, 130, 1, 1, 'en');
INSERT INTO met_language VALUES (null, 'cancel', 'cancel', 0, 131, 1, 1, 'en');
INSERT INTO met_language VALUES (null, 'emailaddress', 'email address', 0, 132, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'telnum', 'cellphone number', 0, 134, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'teluse', 'Phone number is bound', 0, 135, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'telok', 'Please enter the correct phone number', 0, 136, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifyacctel', 'Modify phone binding', 0, 137, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifyinfo', 'Save the data', 0, 138, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailnow', 'Current email:', 0, 139, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'newemail', 'new mail box', 0, 140, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifyaccemail', 'Modify the binding mailbox', 0, 142, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'renewpassword', 'Repeat password', 0, 144, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'inputcode', 'please enter verification code', 0, 145, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'next', 'Next step', 0, 146, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'logintips', 'Username / email / phone', 0, 147, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'otherlogin', 'Other ways to log in', 0, 148, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'logintips1', 'No account? Register now', 0, 149, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'rememberImgCode', 'Resend the verification code', 0, 150, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'relogin', 'Back to login', 0, 151, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'getpasswordtips', 'email / phone number', 0, 152, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'regclose', 'Registration is turned off', 0, 153, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'regfail', 'registration failed', 0, 154, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'codetimeout', 'Verification code has timed out', 0, 155, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'telcheckfail', 'Phone number and SMS verification number is inconsistent', 0, 156, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'regsuc', 'registration success!', 0, 157, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'activesuc', 'Activation successful，please login now', 0, 158, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailvildtips1', 'The verification information is wrong', 0, 159, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailvildtips2', 'Verification information is incorrect or timed out', 0, 160, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'telreg', 'Phone number has been registered', 0, 161, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'Sendfrequent', 'Sent too often, please try again later', 0, 162, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailsuc', 'Mail sent successfully!', 0, 163, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailfail', 'E-mail sent failed, please confirm that the mailbox is correct or contact Webmaster to solve.', 0, 164, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifysuc', 'Successfully modified', 0, 165, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'binding', 'Bind', 0, 166, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'notbound', 'Not bound', 0, 167, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'accnotmodify', 'Account can not be modified', 0, 168, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailsuclink', 'Mail sent successfully! Please click the verification link in the email to complete the operation!', 0, 169, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'bindingok', 'Bind success', 0, 170, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'opfail', 'operation failed', 0, 171, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'modifypasswordsuc', 'Password reset complete!', 0, 172, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'lodpasswordfail', 'The original password is wrong', 0, 173, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror1', 'wrong user name or password', 0, 174, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror2', 'Please open the session!', 0, 175, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror3', 'Authorization failed', 0, 176, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror4', 'unknown mistake', 0, 177, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror6', 'The account is not activated. Please contact the administrator', 0, 174, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailsucpass', 'Password recovery email has been sent to your email address, click the link in the email to reset your password.', 0, 178, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailvildtips3', 'Please enter the correct email or phone number', 0, 179, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'membererror5', 'Failed to send! error code:', 0, 180, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'noempty', 'This item can not be empty', 0, 181, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'usernamecheck', 'Username must be between 2-30 characters', 0, 182, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'passwordcheck', 'The password must be between 6 and 30 characters', 0, 183, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'passwordsame', 'The password input is inconsistent twice', 0, 184, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'emailcheck', 'Please enter the correct email address', 0, 184, 4, 0, 'en');
INSERT INTO met_language VALUES (null, 'Previous_news', 'Previous', 0, 9, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'Next_news', 'Next', 0, 10, 3, 0, 'en');
INSERT INTO met_language VALUES (null, 'close', 'shut down', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'browserupdatetips', 'You are using a obsolete browser. Please upgrade your browser  to enhance your experience.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'newFeedback', 'You received new feedback', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'opfailed', 'operation failed', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'jobPrompt', 'Received a new resume', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'reMessage1', 'Your website', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'reMessage2', ', Please log in as soon as possible to view the website background', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'messagePrompt', 'Received a new message', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'formaterror', 'wrong format', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'listcom', 'recommend', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'listnew', 'update', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'listhot', 'Popular', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'weball', 'All', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'columnall', 'All columns', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsaftips4', 'Binding user confirmation of identity information', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'rnvalidate', 'Real name authentication', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'notauthen', 'Uncertified', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'authen', 'Certified', 0, 9, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'realname', 'Real name', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'idcode', 'ID card No.', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'idvalidok', 'Success of real name authentication', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'idvalidfailed', 'Real name authentication failure', 0, 9, 2, 0, 'en');
INSERT INTO met_language VALUES (null, 'systips1', 'You do not have permission to access this content! Please login to visit!', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'systips2', 'Your user group does not have permission to access this content!', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'usercheckok', 'Verification success!', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'usereadinfo', 'Reading permission value must be greater than 0', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userselectname', 'Tab', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userwenxinclose', 'Wechat login is off', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userwenboclose', 'Weibo login is turned off', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userqqclose', 'QQ login function is closed', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userbuy', 'buy', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'userbuylist', 'Order', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'usesendcode', 'The verification code is', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'usesendcodeinfo', 'Please enter the verification in time', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'feedbackinquiry', 'Online Inquiry', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'templatesusererror', 'The current language template is not configured or the template file does not exist', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'phonecode', 'Get phone verification code', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'phonecodeerror', 'Mobile phone verification code error', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'memberbuytitle', 'Paid upgrade member group', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'img_px_tips', 'Picture size exceeds system limit (picture width not exceeding 2600px)', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'member_cv', 'curriculum vitae', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'please_login', 'Log in first, please!', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'user_agreement', 'User Agreement', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'user_agreement_tips1', 'I have read it carefully', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'user_agreement_tips2', 'And agree to register', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'user_agreement_tips3', 'Please read and tick agree', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'tag', 'Tag', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'columnSearchInfo', 'Please enter the keywords you are interested in.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'advancedSearchInfo', 'Please enter the keywords you are interested in.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'notemptips', 'There is no website template in the current language. Please go to Style-Website Template and select a set of templates.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'AddDate', 'Publish time', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'listsales', 'sales', 0, 0, 0, 0, 'en');

INSERT INTO met_language VALUES (null, 'jsok', 'Successful operation', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'jslang3', 'No records selected', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'delete_information', 'Are you sure you want to delete this information? Can not be restored after deleted.', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'js49', 'Undo', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'weixinunbind', 'Are you sure you want to unbind wechat', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'bindweixin', 'Wechat binding', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'accsaftips5', 'Wechat binding can be used for login account, message notification and other functions', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'bound', 'Bound', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'unbind', 'Unbind', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'weixin_login_error', 'Wechat login is not allowed in the current language', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'login_ok', 'Login successful', 0, 0, 1, 0, 'en');
INSERT INTO met_language VALUES (null, 'new_registe_email_content', 'Your website {webname} has received a registration request from a new user: {user name}. Please log in to the website background to check.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'new_registe_sms_content', 'Your website {webname} has received a registration request from a new user: {user name}. Please log in to the website background to check.', 0, 0, 0, 0, 'en');
INSERT INTO met_language VALUES (null, 'new_regist_notice', 'New member notice', 0, 0, 0, 0, 'en');

#系统配置
INSERT INTO met_config VALUES (null, 'debug','0','','0','0','en');
INSERT INTO met_config VALUES (null, 'metconfig_skin_user', 'metv7', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_listtime', 'Y/m/d', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_contenttime', 'Y-m-d H:i:s', '', 0, 0, 'en');

#SEO-参数设置
INSERT INTO met_config VALUES (null, 'metconfig_hometitle', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_title_type', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_alt', 'MetInfo enterprise content manager system | MetInfo CMS', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_atitle', 'MetInfo CMS', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_linkname', 'MetInfo CMS', '', 0, 0, 'en');
#SEO-TAG标签设置
INSERT INTO met_config VALUES (null, 'tag_show_number', '8', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'tag_show_range', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'tag_search_type', 'module', '', 0, 0, 'en');
#SEO-404页面内容
INSERT INTO met_config VALUES (null, 'metconfig_404content', '404 error, the page is gone. . .', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_data_null', 'The page is gone', '', 0, 0, 'en');
#SEO-优化文字设置
INSERT INTO met_config VALUES (null, 'metconfig_foottext', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_seo', '<p><a href=\"http://www.metinfo.cn/\" target=\"_blank\">MetInfo CMS</a> | <a href=\"http://www.metinfo.cn/idc\" target=\"_blank\">Foreign Host</a> | <a href=\"http://ok.metinfo.cn/\" target=\"_blank\">Domain Registration</a></p>', '', 0, 0, 'en');
#SEO-静态及伪静态配置
INSERT INTO met_config VALUES (null, 'metconfig_webhtm', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_htmtype', 'html', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_htmpagename', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_listhtmltype', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_htmlistname', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_htmway', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_htmlurl', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_pseudo', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_defult_lang', '0', '0', 0, 0, 'en');
#SEO-siteMap
INSERT INTO met_config VALUES (null, 'metconfig_sitemap_auto', '1', '', 0, 0, 'en');

#客服配置
INSERT INTO met_config VALUES (null, 'metconfig_online_skin', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_online_type', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_online_color', '#1baadb', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_onlinetel', '<p>Hotline：</p><p>100-000-0000</p>', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_online_x', '10', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_online_y', '300', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_onlinenameok', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_qq_type', '4', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_taobao_type', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_alibaba_type', '10', '', 0, 0, 'en');

#基本设置-网站信息
INSERT INTO met_config VALUES (null, 'metconfig_webname', 'Website Name', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_logo', '../upload/201801/1515663135.png', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_mobile_logo', '../upload/201807/1532139830.png', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_logo_keyword', 'Logo Keywords', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_keywords', 'Website Keywords', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_description', 'MetInfo enterprise content manager system', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_footright', 'MSN:0000@000.com Email:sales@metinfo.cn', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_footaddress', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_foottel', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_footother', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_icp_info', '', '', 0, 0, 'en');
#基本设置-邮箱配置
INSERT INTO met_config VALUES (null, 'metconfig_fd_fromname', 'MetInfo Co.,Ltd', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_smtp', '61.152.188.131', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_usename', 'test@mail.metinfo.cn', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_password', '123456', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_port', '25', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_way', 'tls', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_fd_word', '', '', '0', '0', 'en');
#基本设置-三方代码设置
INSERT INTO met_config VALUES (null, 'metconfig_headstat', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_footstat','<script>\r\nvar _hmt = _hmt || [];\r\n(function() {\r\n  var hm = document.createElement("script");\r\n  hm.src = "https://hm.baidu.com/hm.js?520556228c0113270c0c772027905838";\r\n  var s = document.getElementsByTagName("script")[0]; \r\n  s.parentNode.insertBefore(hm, s);\r\n})();\r\n</script>','',0,0,'en');
INSERT INTO met_config VALUES (null, 'metconfig_headstat_mobile', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_footstat_mobile','<script>\r\nvar _hmt = _hmt || [];\r\n(function() {\r\n  var hm = document.createElement("script");\r\n  hm.src = "https://hm.baidu.com/hm.js?520556228c0113270c0c772027905838";\r\n  var s = document.getElementsByTagName("script")[0]; \r\n  s.parentNode.insertBefore(hm, s);\r\n})();\r\n</script>','',0,0,'en');

#基本设置-水印图
INSERT INTO met_config VALUES (null, 'metconfig_big_wate', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_wate', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_wate_class', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_wate_img', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_wate_bigimg', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_text_wate', 'www.MetInfo.cn', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_text_size', '10', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_text_bigsize', '15', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_text_color', '#808080', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_text_angle', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_watermark', '0', '', 0, 0, 'en');
#基本设置-缩略图
INSERT INTO met_config VALUES (null, 'metconfig_autothumb_ok', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_thumb_kind', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_x', '800', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_newsimg_y', '500', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_x', '800', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productimg_y', '500', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_x', '800', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_imgs_y', '500', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_x', '800', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productdetail_y', '500', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_x', '800', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_imgdetail_y', '500', '', 0, 0, 'en');

#安全设置-安全与效率
INSERT INTO met_config VALUES (null, 'metconfig_img_rename', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'access_type', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_logs', 0, '', '0', '0', 'en');
INSERT INTO met_config VALUES (null, 'metconfig_auto_play_pc', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_auto_play_mobile', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_memberlogin_code', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_login_code', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_file_maxsize', '5', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_file_format', 'rar|zip|sql|doc|docx|pdf|jpg|xls|png|gif|mp3|mp4|jpeg|bmp|swf|flv|ico|csv', '', 0, 0, 'en');

#用户设置-会员设置
INSERT INTO met_config VALUES (null, 'metconfig_member_use', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_register', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_vecan', '4', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgcolor', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_bgimage', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_agreement', 0, '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_agreement_content', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_bg_range', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_login_box_position', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_new_registe_email_notice', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_to_admin_email', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_new_registe_sms_notice', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_to_admin_sms', '', '', 0, 0, 'en');

#用户设置-邮件内容设置
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_title', '{webname} Member center registration verification', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_reg_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} Member center</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">hello:</p><p style=\"line-height: 23.7999992370605px;\">This is your key message on the {webname} member center, Function is to carry out&nbsp;Member center registration verification, please click on the link below to complete the verification</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">Please click on the link to continue:{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}Member Center</strong></a></p></div></div>', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_title', '{webname} Member center password back', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_password_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} Member Center</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">hello:</p><p style=\"line-height: 23.7999992370605px;\">This is your key message on the {webname} Important message on the member center, Function is to carry out&nbsp;Member center password back, please click on the link below to complete the verification</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">Please click on the link to continue:{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131, 131);\">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}Member Center</strong></a></p></div></div>', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_title', '{webname} Member center to modify the binding mailbox', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_member_email_safety_content', '<div style=\"width:500px;margin:20px auto;\"><div class=\"header clearfix\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; background-color: rgb(255, 255, 255);\"><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname} Member Center</strong></a></div><p>&nbsp;</p><div class=\"content\" style=\"font-family: &#39;lucida Grande&#39;, Verdana, &#39;Microsoft YaHei&#39;; line-height: 23.7999992370605px; border: 1px solid rgb(233, 233, 233); margin: 2px 0px 0px; padding: 30px; background: none 0px 0px repeat scroll rgb(255, 255, 255);\"><p style=\"line-height: 23.7999992370605px;\">hello:</p><p style=\"line-height: 23.7999992370605px;\">This is your key message on the {webname} Important message on the member center, Function is to carry out&nbsp;Member center bound mailbox modification, please click on the link below to complete the verification</p><p style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); margin-top: 15px; margin-bottom: 25px; padding: 15px;\">Please click on the link to continue:{opurl}</p><p style=\"line-height: 23.7999992370605px;\">&nbsp;</p><p class=\"footer\" style=\"line-height: 23.7999992370605px; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(221, 221, 221); padding-top: 6px; margin-top: 25px; color: rgb(131, 131,131);\">Please do not reply to this message, this mailbox is not monitored, you will not get any reply.<br/><br/><a href=\"{weburl}\"><strong style=\"outline: none; cursor: pointer; color: rgb(30, 84, 148);\">{webname}Member Center</strong></a></p></div></div>', '', 0, 0, 'en');
#用户设置-社会化登录
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appid', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_appsecret', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appkey', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_appsecret', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appid', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_qq_appsecret', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_open', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weibo_open', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_qq_open', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appid', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_appsecret', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_weixin_gz_token', '', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_auto_register', '', '', 0, 0, 'en');
#用户设置-实名
INSERT INTO met_config VALUES (null, 'metconfig_member_idvalidate', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_idvalid_key', '', '', 0, 0, 'en');

#页面配置
INSERT INTO met_config VALUES (null, 'metconfig_pnorder', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_product_page', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_img_page', '0', '', 0, 0, 'en');
#页面配置-产品选项卡
INSERT INTO met_config VALUES (null, 'metconfig_productTabname', 'Detailed information', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_1', 'Specification', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_2', 'Packing', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_3', 'Tab four', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productTabname_4', 'Tab five', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_productTabok', '3', '', 0, 0, 'en');
#页面配置-分页条数
INSERT INTO met_config VALUES (null, 'metconfig_product_list', '8', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_news_list', '8', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_download_list', '10', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_img_list', '12', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_job_list', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_message_list', '10', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'metconfig_search_list', '10', '', 0, 0, 'en');

#页面搜索设置
INSERT INTO met_config VALUES (null, 'global_search_range', 'all', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'global_search_type', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'global_search_module', '2', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'global_search_column', '3', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'global_search_weight', '1|2|3|4|5|6', '', 0, 0, 'cn');
INSERT INTO met_config VALUES (null, 'column_search_range', 'parent', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'column_search_type', '0', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'advanced_search_range', 'all', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'advanced_search_type', '1', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'advanced_search_column', '3', '', 0, 0, 'en');
INSERT INTO met_config VALUES (null, 'advanced_search_linkage', '1', '', 0, 0, 'en');

INSERT INTO met_lang VALUES(null,'English','1','2','en','en','en.gif','','0','0','html','','en');

INSERT INTO met_admin_array VALUES(4,'Member','','0','','0','0','1','1','en','');
INSERT INTO met_admin_array VALUES(5,'Agents','','0','','0','0','2','1','en','');

INSERT INTO `met_user_group` VALUES(4, 'Member', 1, 'en');
INSERT INTO `met_user_group` VALUES(5, 'Agents', 2, 'en');