package constant

const (
	RequestID                       = "RequestID"
	FC_REGION                       = "FC_REGION"
	ALIBABA_CLOUD_ACCESS_KEY_ID     = "ALIBABA_CLOUD_ACCESS_KEY_ID"
	ALIBABA_CLOUD_ACCESS_KEY_SECRET = "ALIBABA_CLOUD_ACCESS_KEY_SECRET"
	ALIBABA_CLOUD_SECURITY_TOKEN    = "ALIBABA_CLOUD_SECURITY_TOKEN"
)
