start_thinkjs:
  default:
    languages:
      - nodejs20
    steps:
      - run: npm install --production
        path: ./code
  defaultBuilder:
    languages:
      - nodejs20
    steps:
      - run: npm install --production
        path: ./code