<?php

$tphtml = array(
'meta.php' => '头部Meta信息页面',
	'404.php' => '网站404页面',
	'activelist.php' => '用户列表页面',
	'addxinzhi.php' => '文章添加页面',
	'appendanswer.php' => '追加回答页面',
	'ask.php' => '提问页面',
			'category.php' => '分类列表页面',
			'catlist.php' => '文章分类页面',
			'doing.php' => '网站动态页面',
			'editanswer.php' => '编辑回答页面',
			'editimg.php' => '修改头像页面',
			'editquestion.php' => '修改问题页面',
			'editxinzhi.php' => '修改新知页面',
        'expert.php'=> '专家列表',
 'footer.php'=> '底部公共页面',
 'getpass.php'=> '忘记密码',
 'giftlist.php'=> '礼物列表',
 'header.php'=> '头部公共页面',
 'help.php'=> '帮助页面',
 'index.php'=> '首页',
 'login.php'=> '登陆页面',
 'maketag.php'=> '自动生成标签页',
 'message.php'=> '私信页面',
 'myanswer.php'=> '我的回答页面',
 'myask.php'=> '我的提问页面',
 'mycategory.php'=> '我擅长的分类页面',
 'myfollower.php'=> '关注我的人页面',
 'myrecommend.php'=> '我的推荐页面',
 'myscore.php'=> '个人中心页面',
 'myset.php'=> '我的设置页面',
 'myxinzhi.php'=> '我的新知页面',
 'new.php'=> '最新问题页面',
 'nosolve.php'=> '未解决页面',
 'note.php'=> '通知详情页',
 'notelist.php'=> '通知列表页面',
 'poplogin.php'=> '弹出登陆框模板页面',
 'profile.php'=> '修改个人资料页面',
 'register.php'=> '注册页面',
 'scorelist.php'=> '达人榜页面',
 'search.php'=> '搜索列表页',
 'sendmsg.php'=> '发私信',
 'solve.php'=> '已解决问题页面',
 'space.php'=> '网友个人中心',
 'space_answer.php'=> '网友问题回答页面',
 'space_ask.php'=> '网友问题列表页面',
 'space_menu.php'=> '网友页面左侧模板页',
 'tag.php'=> '标签页面',
 'tip.php'=> '网站信息提示页面',
 'topic.php'=> '文章首页',
'topichot.php'=> '热文列表',
 'topicone.php'=> '文章详情页',
 'topictag.php'=> '文章标签页',
 'uppass.php'=> '修改个人密码',
 'user_menu.php'=> '个人中心左侧模板',

 'usercard.php'=> '鼠标滑到头像显示用户卡片页面',

 'userxinzhi.php'=> '用户个人发布的文章列表页面',
 'viewmessage.php'=> '查看私信详情'


);

?>