# Generated by Django 3.1.7 on 2021-03-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('publish', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='发布时间')),
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='文章标题')),
                ('desc', models.TextField(verbose_name='文章描述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('watched', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('sort', models.IntegerField(default=999, verbose_name='排序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('username', models.CharField(max_length=50, verbose_name='用户')),
                ('qq', models.CharField(blank=True, max_length=13, null=True, verbose_name='QQ号')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article_title', models.CharField(max_length=50, verbose_name='文章')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articlemodel')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.commentsmodel', verbose_name='父级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categorymodel', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tag',
            field=models.ManyToManyField(to='blog.TagsModel', verbose_name='标签'),
        ),
    ]
