# Generated by Django 3.1.7 on 2021-03-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210303_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='count',
        ),
    ]
