# Generated by Django 3.1.7 on 2021-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_categorymodel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='pid',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='回复'),
        ),
    ]
