#!/usr/bin/env bash
set +e

mkdir -p /tmp/var/sessions/
mkdir -p /tmp/log/nginx/
mkdir -p /tmp/var/nginx/

chown -R www-data:www-data /mnt/auto/ecshop

echo "start php-fpm"
php-fpm7.2 -c /code/root/usr/lib/php/7.2/php.ini-production -y /code/root/etc/php/7.2/fpm/php-fpm.conf

echo "start nginx"
nginx -c /code/root/etc/nginx/nginx.conf

sleep 5

while true
do
    echo "check nginx and php-fpm process ...."
    nginx_server=`ps aux | grep nginx | grep -v grep`
    if [ ! "$nginx_server" ]; then
        echo "restart nginx ..."
        nginx -c /code/root/etc/nginx/nginx.conf
    fi
    php_fpm_server=`ps aux | grep php-fpm | grep -v grep`
    if [ ! "$php_fpm_server" ]; then
        echo "restart php-fpm ..."
        php-fpm7.2 -c /code/root/usr/lib/php/7.2/php.ini-production -y /code/root/etc/php/7.2/fpm/php-fpm.conf
    fi
    sleep 10
done