<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_head\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\',bigclass =\'0\'',
  1 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_product\',value=\'\',defaultvalue=\'\',valueinfo =\'首页产品区块\',tips=\'\',bigclass =\'0\'',
  2 => 'pos =\'3\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'news_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  3 => 'pos =\'2\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_download\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  4 => 'pos =\'0\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'navbarok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉菜单\',tips=\'\',bigclass =\'51\'',
  5 => 'pos =\'1\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'68\'',
  6 => 'pos =\'3\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column3_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'94\'',
  7 => 'pos =\'2\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'download\',value=\'立即下载\',defaultvalue=\'立即下载\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'101\'',
  8 => 'pos =\'2\',no_order=\'3\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  9 => 'pos =\'0\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_ml\',value=\'10\',defaultvalue=\'10\',valueinfo =\'导航间距\',tips=\'默认是0，仅支持5的倍数（0/5/10/15/20...最大50）<br/>不同网站的导航数量不同，根据需求适当调整间距，让网站更协调。\',bigclass =\'51\'',
  10 => 'pos =\'1\',no_order=\'3\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_product_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'68\'',
  11 => 'pos =\'3\',no_order=\'3\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'94\'',
  12 => 'pos =\'2\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$浏览模式$T$1$M$详情模式$T$0\',name =\'img_listlook_style\',value=\'1\',defaultvalue=\'1\',valueinfo =\'查看模式\',tips=\'浏览模式为在列表页浏览图片，详情模式为点击进入详情页\',bigclass =\'15\'',
  13 => 'pos =\'0\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'下拉菜单全部\',tips=\'仅在手机端显示\',bigclass =\'51\'',
  14 => 'pos =\'1\',no_order=\'4\',type=\'6\',style=\'3\',selectd=\'\',name =\'index_product_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'\',bigclass =\'68\'',
  15 => 'pos =\'3\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'94\'',
  16 => 'pos =\'0\',no_order=\'5\',type=\'4\',style=\'3\',selectd=\'$M$鼠标经过$T$1$M$点击展开$T$0\',name =\'navhoverok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉方式\',tips=\'\',bigclass =\'51\'',
  17 => 'pos =\'2\',no_order=\'5\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_job\',value=\'\',defaultvalue=\'\',valueinfo =\'招聘模块\',tips=\'\',bigclass =\'0\'',
  18 => 'pos =\'1\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'栏目列表代表文字\',tips=\'\',bigclass =\'68\'',
  19 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\',bigclass =\'94\'',
  20 => 'pos =\'0\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$头部$T$1$M$底部$T$0\',name =\'langlist_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'多语言位置\',tips=\'\',bigclass =\'51\'',
  21 => 'pos =\'2\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'cvtitle\',value=\'在线应聘\',defaultvalue=\'在线应聘\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'66\'',
  22 => 'pos =\'1\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'浏览器宽度大于1600像素时\',bigclass =\'68\'',
  23 => 'pos =\'3\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\',bigclass =\'94\'',
  24 => 'pos =\'2\',no_order=\'7\',type=\'1\',style=\'3\',selectd=\'\',name =\'subcolumn_nav\',value=\'\',defaultvalue=\'\',valueinfo =\'子栏目设置\',tips=\'\',bigclass =\'0\'',
  25 => 'pos =\'0\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'langlist1_icon_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言国旗开关\',tips=\'\',bigclass =\'51\'',
  26 => 'pos =\'1\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'浏览器宽度大于992像素小于1600像素时\',bigclass =\'68\'',
  27 => 'pos =\'3\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'news_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表文章类型\',tips=\'\',bigclass =\'94\'',
  28 => 'pos =\'3\',no_order=\'8\',type=\'1\',style=\'3\',selectd=\'\',name =\'downlaod_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  29 => 'pos =\'2\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_2\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块开关\',tips=\'\',bigclass =\'17\'',
  30 => 'pos =\'0\',no_order=\'8\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_position\',value=\'\',defaultvalue=\'\',valueinfo =\'当前位置\',tips=\'\',bigclass =\'0\'',
  31 => 'pos =\'1\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'浏览器宽度大于768像素小于992像素时\',bigclass =\'68\'',
  32 => 'pos =\'2\',no_order=\'9\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_news\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  33 => 'pos =\'3\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_title\',value=\'为你推荐\',defaultvalue=\'为你推荐\',valueinfo =\'侧栏下载列表标题\',tips=\'\',bigclass =\'8\'',
  34 => 'pos =\'0\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'position_text\',value=\'你的位置\',defaultvalue=\'你的位置\',valueinfo =\'当前位置标题\',tips=\'\',bigclass =\'19\'',
  35 => 'pos =\'1\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'浏览器宽度小于768像素时\',bigclass =\'68\'',
  36 => 'pos =\'2\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_imgok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'图片开关\',tips=\'\',bigclass =\'6\'',
  37 => 'pos =\'3\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_downloadlist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏下载列表数量\',tips=\'\',bigclass =\'8\'',
  38 => 'pos =\'0\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区域开关\',tips=\'\',bigclass =\'19\'',
  39 => 'pos =\'1\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_allnum\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'每个列表调用信息最多条数\',bigclass =\'68\'',
  40 => 'pos =\'0\',no_order=\'11\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_foot\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\',bigclass =\'0\'',
  41 => 'pos =\'3\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'download_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表下载类型\',tips=\'\',bigclass =\'8\'',
  42 => 'pos =\'1\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'index_product_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'列表信息调用类型，【推荐】可以在添加或管理文章列表时设置。\',bigclass =\'68\'',
  43 => 'pos =\'0\',no_order=\'12\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'link_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'友情链接开关\',tips=\'\',bigclass =\'1\'',
  44 => 'pos =\'3\',no_order=\'12\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'download_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'8\'',
  45 => 'pos =\'1\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_w\',value=\'484\',defaultvalue=\'484\',valueinfo =\'缩略图宽\',tips=\'默认为484px\',bigclass =\'68\'',
  46 => 'pos =\'0\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'footlink_title\',value=\'友情链接\',defaultvalue=\'友情链接\',valueinfo =\'友情链接标题\',tips=\'\',bigclass =\'1\'',
  47 => 'pos =\'3\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'downloadsidebar_column_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'8\'',
  48 => 'pos =\'1\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_h\',value=\'300\',defaultvalue=\'300\',valueinfo =\'缩略图高\',tips=\'默认为300px\',bigclass =\'68\'',
  49 => 'pos =\'0\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'$M$底部$T$0$M$顶部$T$1\',name =\'cn1_position\',value=\'0\',defaultvalue=\'0\',valueinfo =\'简繁体切换按钮位置\',tips=\'\',bigclass =\'1\'',
  50 => 'pos =\'3\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'sidebar_downloadlist_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'8\'',
  51 => 'pos =\'1\',no_order=\'14\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_about\',value=\'\',defaultvalue=\'\',valueinfo =\'首页简介区块\',tips=\'\',bigclass =\'0\'',
  52 => 'pos =\'0\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'cn1_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'简繁体切换开关\',tips=\'\',bigclass =\'1\'',
  53 => 'pos =\'3\',no_order=\'15\',type=\'1\',style=\'3\',selectd=\'\',name =\'img_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  54 => 'pos =\'1\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'90\'',
  55 => 'pos =\'3\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏图片列表开关\',tips=\'\',bigclass =\'22\'',
  56 => 'pos =\'0\',no_order=\'16\',type=\'1\',style=\'3\',selectd=\'\',name =\'global\',value=\'\',defaultvalue=\'\',valueinfo =\'全局参数\',tips=\'\',bigclass =\'0\'',
  57 => 'pos =\'1\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'90\'',
  58 => 'pos =\'3\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏图片列表标题\',tips=\'\',bigclass =\'22\'',
  59 => 'pos =\'0\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_font\',value=\'\',defaultvalue=\'\',valueinfo =\'页面字体\',tips=\'非特殊语种，建议留空使用模板默认字体\',bigclass =\'58\'',
  60 => 'pos =\'1\',no_order=\'17\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'区块内容\',tips=\'\',bigclass =\'90\'',
  61 => 'pos =\'3\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'img_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表图片类型\',tips=\'\',bigclass =\'22\'',
  62 => 'pos =\'1\',no_order=\'18\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_news\',value=\'\',defaultvalue=\'\',valueinfo =\'首页新闻区块\',tips=\'\',bigclass =\'0\'',
  63 => 'pos =\'0\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'sub_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'页面文字\',tips=\'\',bigclass =\'58\'',
  64 => 'pos =\'3\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表图片数量\',tips=\'\',bigclass =\'22\'',
  65 => 'pos =\'1\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'40\'',
  66 => 'pos =\'0\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'page_ajax_next\',value=\'加载更多\',defaultvalue=\'加载更多\',valueinfo =\'分页文字\',tips=\'无刷新分页默认文字\',bigclass =\'58\'',
  67 => 'pos =\'3\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'imgbar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'22\'',
  68 => 'pos =\'1\',no_order=\'20\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_news_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'40\'',
  69 => 'pos =\'0\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'nodata\',value=\'没有数据了\',defaultvalue=\'没有数据了\',valueinfo =\'无数据提示\',tips=\'\',bigclass =\'58\'',
  70 => 'pos =\'3\',no_order=\'21\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'22\'',
  71 => 'pos =\'1\',no_order=\'21\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news1\',value=\'4\',defaultvalue=\'4\',valueinfo =\'调用栏目\',tips=\'调用当前栏目的内容列表\',bigclass =\'40\'',
  72 => 'pos =\'0\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'search_placeholder\',value=\'请输入内容关键词\',defaultvalue=\'请输入内容关键词\',valueinfo =\'搜索文字\',tips=\'\',bigclass =\'58\'',
  73 => 'pos =\'3\',no_order=\'22\',type=\'1\',style=\'3\',selectd=\'\',name =\'product_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块侧边栏\',tips=\'\',bigclass =\'0\'',
  74 => 'pos =\'1\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'调用条数\',tips=\'\',bigclass =\'40\'',
  75 => 'pos =\'0\',no_order=\'22\',type=\'9\',style=\'3\',selectd=\'\',name =\'first_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'模板主色调\',tips=\'\',bigclass =\'58\'',
  76 => 'pos =\'3\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_title\',value=\'热门推荐\',defaultvalue=\'热门推荐\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'29\'',
  77 => 'pos =\'1\',no_order=\'23\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'home_news_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'40\'',
  78 => 'pos =\'0\',no_order=\'23\',type=\'4\',style=\'3\',selectd=\'当前窗口打开$T$target=_self$M$新窗口打开$T$target=_blank\',name =\'urlnew\',value=\'target=_self\',defaultvalue=\'target=_self\',valueinfo =\'内容列表链接打开方式\',tips=\'列表页链接打开方式可在栏目管理中对每个栏目进行单独设置\',bigclass =\'58\'',
  79 => 'pos =\'3\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'调用条数\',tips=\'\',bigclass =\'29\'',
  80 => 'pos =\'0\',no_order=\'24\',type=\'1\',style=\'3\',selectd=\'\',name =\'banner\',value=\'\',defaultvalue=\'\',valueinfo =\'banner设置\',tips=\'\',bigclass =\'0\'',
  81 => 'pos =\'1\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_more\',value=\'MORE\',defaultvalue=\'MORE\',valueinfo =\'更多文字\',tips=\'\',bigclass =\'40\'',
  82 => 'pos =\'3\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'product_sidebar_piclist_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'29\'',
  83 => 'pos =\'0\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$提示$T$1\',name =\'info\',value=\'1\',defaultvalue=\'1\',valueinfo =\'提示\',tips=\'此banner是图片不适合设置高度，如果觉得banner尺寸不合适请更换banner尺寸\',bigclass =\'34\'',
  84 => 'pos =\'1\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'显示$T$1$M$隐藏$T$0\',name =\'home_news_img_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示图片\',tips=\'默认为显示\',bigclass =\'40\'',
  85 => 'pos =\'3\',no_order=\'26\',type=\'4\',style=\'3\',selectd=\'当前一级栏目内容列表$T$1$M$TAG标签聚合$T$0\',name =\'product_sidebar_content\',value=\'1\',defaultvalue=\'1\',valueinfo =\'调用内容\',tips=\'默认调用当前栏目内容列表\',bigclass =\'29\'',
  86 => 'pos =\'0\',no_order=\'26\',type=\'9\',style=\'3\',selectd=\'\',name =\'page_top_bgcolor\',value=\'#ccc\',defaultvalue=\'#ccc\',valueinfo =\'内页无banner背景色\',tips=\'\',bigclass =\'34\'',
  87 => 'pos =\'1\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_img_maxnum\',value=\'80\',defaultvalue=\'80\',valueinfo =\'描述文字字数限制\',tips=\'默认为80个字符\',bigclass =\'40\'',
  88 => 'pos =\'0\',no_order=\'27\',type=\'9\',style=\'3\',selectd=\'\',name =\'bannersub_color\',value=\'#fff\',defaultvalue=\'#fff\',valueinfo =\'内页无banner字体色\',tips=\'\',bigclass =\'34\'',
  89 => 'pos =\'1\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_w\',value=\'200\',defaultvalue=\'200\',valueinfo =\'缩略图宽\',tips=\'默认为200px\',bigclass =\'40\'',
  90 => 'pos =\'0\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'btn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'电脑端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'34\'',
  91 => 'pos =\'1\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_h\',value=\'125\',defaultvalue=\'125\',valueinfo =\'缩略图高\',tips=\'默认为125px\',bigclass =\'40\'',
  92 => 'pos =\'0\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'mbtn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'手机端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'34\'',
  93 => 'pos =\'1\',no_order=\'29\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_case\',value=\'\',defaultvalue=\'\',valueinfo =\'首页合作伙伴\',tips=\'\',bigclass =\'0\'',
  94 => 'pos =\'1\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'81\'',
  95 => 'pos =\'0\',no_order=\'30\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_contact\',value=\'\',defaultvalue=\'\',valueinfo =\'底部联系信息设置\',tips=\'\',bigclass =\'0\'',
  96 => 'pos =\'1\',no_order=\'31\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'81\'',
  97 => 'pos =\'0\',no_order=\'31\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_tel\',value=\'\',defaultvalue=\'\',valueinfo =\'服务热线\',tips=\'\',bigclass =\'103\'',
  98 => 'pos =\'1\',no_order=\'32\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_case_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\',bigclass =\'81\'',
  99 => 'pos =\'0\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_dsc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字\',tips=\'\',bigclass =\'103\'',
  100 => 'pos =\'1\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'默认调用8条\',bigclass =\'81\'',
  101 => 'pos =\'0\',no_order=\'33\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_wx_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'微信\',tips=\'\',bigclass =\'103\'',
  102 => 'pos =\'1\',no_order=\'34\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'home_case_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'81\'',
  103 => 'pos =\'0\',no_order=\'34\',type=\'7\',style=\'3\',selectd=\'\',name =\'footinfo_wx\',value=\'\',defaultvalue=\'\',valueinfo =\'微信二维码\',tips=\'\',bigclass =\'103\'',
  104 => 'pos =\'0\',no_order=\'35\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_qq_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ\',tips=\'\',bigclass =\'103\'',
  105 => 'pos =\'1\',no_order=\'35\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num_xxl\',value=\'8\',defaultvalue=\'8\',valueinfo =\'大尺寸电脑显示列数\',tips=\'浏览器宽度大于1600像素时\',bigclass =\'81\'',
  106 => 'pos =\'0\',no_order=\'36\',type=\'4\',style=\'3\',selectd=\'$M$个人QQ$T$1$M$企业营销QQ$T$2\',name =\'foot_info_qqtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ类型\',tips=\'个人QQ和企业营销QQ超链接结构不一样，因此请务必选择正确。\',bigclass =\'103\'',
  107 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num_lg\',value=\'6\',defaultvalue=\'6\',valueinfo =\'普通电脑显示列数\',tips=\'浏览器宽度大于1024像素小于1600像素时\',bigclass =\'81\'',
  108 => 'pos =\'0\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_qq\',value=\'\',defaultvalue=\'\',valueinfo =\'QQ号码\',tips=\'点击QQ链接可直接对话，需要先到 shang.qq.com 免费开通。<br/>企业营销QQ 无需开通\',bigclass =\'103\'',
  109 => 'pos =\'1\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num_md\',value=\'4\',defaultvalue=\'4\',valueinfo =\'平板显示列数\',tips=\'浏览器宽度大于768像素小于1024像素时\',bigclass =\'81\'',
  110 => 'pos =\'0\',no_order=\'38\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_sina_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'新浪微博\',tips=\'\',bigclass =\'103\'',
  111 => 'pos =\'1\',no_order=\'38\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'浏览器宽度小于768像素时\',bigclass =\'81\'',
  112 => 'pos =\'1\',no_order=\'39\',type=\'4\',style=\'3\',selectd=\'纯展示$T$0$M$超链接$T$1\',name =\'home_case_linkok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示方式\',tips=\'默认为超链接\',bigclass =\'81\'',
  113 => 'pos =\'0\',no_order=\'39\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_sina\',value=\'\',defaultvalue=\'\',valueinfo =\'新浪微博网址\',tips=\'请输入微博网址\',bigclass =\'103\'',
  114 => 'pos =\'1\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgw\',value=\'320\',defaultvalue=\'320\',valueinfo =\'缩略图宽\',tips=\'默认为320px\',bigclass =\'81\'',
  115 => 'pos =\'0\',no_order=\'40\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_twitterok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'twitter（推特）\',tips=\'\',bigclass =\'103\'',
  116 => 'pos =\'1\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgh\',value=\'200\',defaultvalue=\'200\',valueinfo =\'缩略图高\',tips=\'默认为200px\',bigclass =\'81\'',
  117 => 'pos =\'0\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_twitter\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter网址\',tips=\'\',bigclass =\'103\'',
  118 => 'pos =\'0\',no_order=\'42\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_googleok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'google+\',tips=\'\',bigclass =\'103\'',
  119 => 'pos =\'0\',no_order=\'43\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_google\',value=\'\',defaultvalue=\'\',valueinfo =\'google+网址\',tips=\'\',bigclass =\'103\'',
  120 => 'pos =\'0\',no_order=\'44\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_facebookok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'Facebook\',tips=\'\',bigclass =\'103\'',
  121 => 'pos =\'0\',no_order=\'45\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_facebook\',value=\'\',defaultvalue=\'\',valueinfo =\'Facebook网址\',tips=\'\',bigclass =\'103\'',
  122 => 'pos =\'0\',no_order=\'46\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_emailok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'邮箱\',tips=\'\',bigclass =\'103\'',
  123 => 'pos =\'0\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱地址\',tips=\'\',bigclass =\'103\'',
);
$no='metv7';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>